engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
    channel: "eslint-3"
  markdownlint:
    enabled: true

ratings:
  paths:
  - "*.md"
  - "src/**.js"
