language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
env:
  - TEST_SUITE=test
  - TEST_SUITE=test/e2e/connect
  - TEST_SUITE=test/e2e/express
  - TEST_SUITE=test/e2e/restify

matrix:
  include:
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="firefox"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="chrome"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="internet explorer"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="safari"

script:
  - npm test $TEST_SUITE
