language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
env:
  - TEST_SUITE=test
  - TEST_SUITE=test/e2e/connect
  - TEST_SUITE=test/e2e/express
  - TEST_SUITE=test/e2e/restify

matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_SUITE=test/e2e/browser BROWSER="firefox"
  - env: TEST_SUITE=test/e2e/browser BROWSER="chrome"
  - env: TEST_SUITE=test/e2e/browser BROWSER="internet explorer" PLATFORM="Windows 10"
  - env: TEST_SUITE=test/e2e/browser BROWSER="safari" PLATFORM="macOS 10.12"
  include:
  - node_js: "node"
    addons:
      code_climate: true
    env: TEST_SUITE=test CODECLIMATE="true"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="firefox"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="chrome"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="internet explorer" PLATFORM="Windows 10"
  - node_js: "node"
    addons:
      sauce_connect: true
    env: TEST_SUITE=test/e2e/browser BROWSER="safari" PLATFORM="macOS 10.12"

script:
  - npm test $TEST_SUITE

after_success:
  - if test -n "$CODECLIMATE" ; then
      export ;
      npm install -g codeclimate-test-reporter nyc ;
      nyc report --reporter=text-lcov | codeclimate-test-reporter ;
    fi
